stages:
  - clone
  - build_and_publish
  - deploy

variables:
  GIT_CLONE_PATH: "./release/$CI_COMMIT_BRANCH"
  GIT_STRATEGY: none

clone_repo:
  stage: clone
  script:
    - echo "Cloning"
    - dir
    - git --version
    - git clone --branch REL_FE_0_4_1 http://192.168.0.102:4000/root/fe.git C:/Users/commonuser/Desktop/release/$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^REL_/

build_website:
  stage: build_and_publish
  script:
    - pwd
    - cd C:\Users\commonuser\Desktop\release\$CI_COMMIT_BRANCH\build
    - ./build.sh
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^REL_/
  dependencies:
    - clone_repo

deploy_website:
  stage: deploy
  script:
    - cd C:\Users\commonuser\Desktop\release\$CI_COMMIT_BRANCH\deploy
    - ./deploy.ps1
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^REL_/
  dependencies:
    - build_website
